export interface MobileMoneyPaymentParameters {
  /**
   * * The amount to be paid
   */
  price: number
  /**
   * This is the network of the mobile money account that would be making the payment (your customer).
   */
  network: string
  /**
   * This is the mobile money account the payments shall end up in. (your account).
   */
  recipient_number: string
  /**
   * This is the mobile money account that would be making the payment (your customers).
   */
  sender: string
  /**
   * This denotes the direction of cash flow. For example, rmta can be understood as an acronym of the phrase ‘receive mtn to airtel’, which means you would be receiving money to your Airtel account (the recipient number) from an MTN number(the sender). This format would hold for all transaction requests sent to the API. Do not forget to append the r at beginning.
   */
  option: string
  /**
   * This optional parameter can be added to track the status of a transaction after it has been completed by use of our check status endpoint. Please note that the order ID is not the same as the transaction ID returned after a transaction request.
   */
  orderID?: string
  /**
   * This is the token generated by Vodafone users in order to complete mobile money payments. This parameter is only required when the payment is to be made by a Vodafone user.
   */
  token?: string
}

export interface MobileMoneyPaymentResponse {
  code: number
  status: string
  id: string
}

export interface SendTokensParameters {
  price: number
  recipient: string
  sender: string
}

export interface SendTokensResponse extends MobileMoneyPaymentResponse {}

export interface ReceiveTokensParameters {
  /**
   * The option for this request should be set_callback_url
   */
  option: string
  /**
   * The account making the payment
   */
  sender: string
  /**
   * Your callback URL
   */
  callback_url: string
}

export interface ReceiveTokensResponse {
  code: string
  status: string
}

export interface CheckTransactionStatusResponse {
  code: number
  hash: string
  status: string
}

export interface CheckAccountBalanceResponse
  extends CheckTransactionStatusResponse {}

export interface ValidateAccountResponse extends ReceiveTokensResponse {
  username: string
  message: string
}
